### ISSUE TITLE
"uninitialized constant Net::HTTP" when RAILS_ENV=production

### ISSUE THREAD

**Issue by hiddenwaffle** [AzureAD/omniauth-azure-activedirectory#33]
## Summary

When using this gem with Rails 5.1.2 with Ruby 2.4.1, opening path /auth/azureactivedirectory gives this error:
```
NameError (uninitialized constant Net::HTTP):
omniauth-azure-activedirectory (1.0.0) lib/omniauth/strategies/azure_activedirectory.rb:169:in `fetch_openid_config'
```
The error does not occur in development mode. It only occurs when RAILS_ENV=production. Tested on Ubuntu 16.04 and the macOS Sierra.

## Steps to reproduce

1. Create a new test project:
```
rails new testproject
cd testproject
```
2. Add gem to Gemfile:
```Ruby
gem 'omniauth-azure-activedirectory'
```
3. Update gems and Gemfile.lock from Gemfile:
```
bundle
```
4. Add omniauth.rb to config/initializers:
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :azure_activedirectory, ENV['AAD_CLIENT_ID'], ENV['AAD_TENANT']
  # other providers here
end
```
5. Run server:
```
AAD_CLIENT_ID=clientId AAD_TENANT=tenantId RAILS_ENV=production bin/rails server
```
6. Navigate to http://localhost:3000/auth/azureactivedirectory
7. Error should appear in logs/production.log:
```
...
NameError (uninitialized constant Net::HTTP):
omniauth-azure-activedirectory (1.0.0) lib/omniauth/strategies/azure_activedirectory.rb:169:in `fetch_openid_config'
...
```
## Workaround
I was able to successfully work around this issue by requiring the module in my application.rb file:
```ruby
require 'net/http'
```
## Root Cause
I suspect that something runs in Rails development that that requires net/http ahead of time. Nevertheless, do you think that the azure_activedirectory.rb file the omniauth-azure-activedirectory gem should require net/http on its own since it refers to the constant in the fetch_openid_config method on line 169 of that file?

**Comment by hiddenwaffle** [comment]
Never mind, I see that PR #31 will fix this.
